<div class="space-y-6">
    <x-page-header title="Oefeningen" description="Beheer de gedeelde oefeningenbibliotheek."><x-slot:actions><div class="flex flex-wrap items-center gap-2"><flux:button href="{{ route('coach.exercises.export') }}">Exporteer</flux:button>@can('create', \App\Models\ExerciseLibraryItem::class)<flux:button variant="primary" wire:click="edit">Nieuwe oefening</flux:button>@endcan</div></x-slot:actions></x-page-header>
    @if(session('exercise-saved'))<flux:callout variant="success">{{ session('exercise-saved') }}</flux:callout>@endif
    @if(session()->has('exercise-imported'))<flux:callout variant="success" icon="check-circle" heading="Import voltooid">{{ session('exercise-imported') }}</flux:callout>@endif
    @if(session('exercise-import-error'))<flux:callout variant="danger" icon="x-circle" heading="Importeren mislukt">{{ session('exercise-import-error') }}</flux:callout>@endif
    @can('create', \App\Models\ExerciseLibraryItem::class)<form action="{{ route('coach.exercises.import') }}" method="POST" enctype="multipart/form-data" class="flex flex-wrap items-end gap-3 rounded-xl border border-primary-100 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900">@csrf<flux:field class="min-w-64 flex-1"><flux:label>Oefeningen importeren</flux:label><input name="archive" type="file" accept="application/zip,.zip" required class="block w-full text-sm" /><flux:description>Gebruik een eerder geëxporteerd ZIP-bestand.</flux:description><flux:error name="archive" /></flux:field><flux:button type="submit" variant="primary">Importeren</flux:button></form>@endcan
    <div class="grid gap-3 md:grid-cols-2"><flux:input wire:model.live.debounce.300ms="search" placeholder="Zoek oefening" icon="magnifying-glass" /><flux:select wire:model.live="category"><flux:select.option value="">Alle categorieën</flux:select.option>@foreach($categories as $item)<flux:select.option :value="$item">{{ $item }}</flux:select.option>@endforeach</flux:select></div>
    @if($showForm)
        <form wire:submit="save" class="grid gap-4 rounded-xl border border-primary-100 bg-white p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 md:grid-cols-2">
            <flux:field><flux:label>Naam</flux:label><flux:input wire:model="name" /><flux:error name="name" /></flux:field><flux:field><flux:label>Categorie</flux:label><flux:input wire:model="formCategory" placeholder="bijv. passing" /><flux:error name="formCategory" /></flux:field>
            <flux:field><flux:label>Scope</flux:label><flux:select wire:model="scope"><flux:select.option value="both">Individueel én team</flux:select.option><flux:select.option value="team">Alleen team</flux:select.option><flux:select.option value="individual">Alleen individueel</flux:select.option></flux:select></flux:field><flux:field><flux:label>Standaardduur (min.)</flux:label><flux:input type="number" min="1" wire:model="duration" /></flux:field>
            <flux:field class="md:col-span-2"><flux:label>Korte samenvatting</flux:label><flux:textarea wire:model="description" rows="2" /><flux:error name="description" /></flux:field><flux:field class="md:col-span-2"><flux:label>Uitvoering</flux:label><flux:textarea wire:model="execution" rows="3" /><flux:error name="execution" /></flux:field>
            <flux:field><flux:label>Doel</flux:label><flux:input wire:model="objective" /></flux:field><flux:field><flux:label>Organisatie</flux:label><flux:input wire:model="organization" /></flux:field><flux:field><flux:label>Min. spelers</flux:label><flux:input type="number" wire:model="minPlayers" /></flux:field><flux:field><flux:label>Max. spelers</flux:label><flux:input type="number" wire:model="maxPlayers" /></flux:field><flux:field><flux:label>Baskets</flux:label><flux:input type="number" wire:model="baskets" /></flux:field><flux:field><flux:label>Intensiteit</flux:label><flux:input wire:model="intensity" /></flux:field>
            <flux:field class="md:col-span-2"><flux:label>Coaching points (één per regel)</flux:label><flux:textarea wire:model="coachingPoints" rows="3" /></flux:field><flux:field class="md:col-span-2"><flux:label>Constraints (één per regel)</flux:label><flux:textarea wire:model="constraints" rows="2" /></flux:field><flux:field><flux:label>Tags</flux:label><flux:input wire:model="tags" /></flux:field><flux:field><flux:label>Afbeelding of PDF</flux:label><input type="file" wire:model="media" accept="image/jpeg,image/png,image/webp,application/pdf" class="block w-full text-sm" /></flux:field><flux:field><flux:label>Videolink</flux:label><flux:input wire:model="videoUrl" type="url" /></flux:field><flux:field><flux:label>Externe link</flux:label><flux:input wire:model="externalUrl" type="url" /></flux:field><flux:field class="md:col-span-2"><flux:label>Interne coachnotities</flux:label><flux:textarea wire:model="coachNotes" rows="2" /></flux:field>
            <div class="flex gap-2 md:col-span-2"><flux:button variant="primary" type="submit">Opslaan</flux:button><flux:button type="button" wire:click="edit">Opnieuw beginnen</flux:button></div>
        </form>
    @endif
    <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3">@forelse($exercises as $exercise)<article wire:key="exercise-{{ $exercise->id }}" class="rounded-xl border border-primary-100 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><p class="text-xs font-semibold uppercase text-flash-orange">{{ $exercise->category }}</p><h2 class="mt-1 font-semibold text-primary-900 dark:text-white">{{ $exercise->name }}</h2><p class="mt-2 text-sm text-zinc-600 dark:text-zinc-300">{{ $exercise->description }}</p><div class="mt-4 flex gap-2">@can('update', $exercise)<flux:button size="sm" wire:click="edit({{ $exercise->id }})">Bewerken</flux:button><flux:button size="sm" variant="danger" wire:click="archive({{ $exercise->id }})">Archiveren</flux:button>@endcan</div></article>@empty<p class="text-sm text-zinc-500">Nog geen actieve oefeningen. Maak je eerste oefening.</p>@endforelse</div>
</div>
